In [1]:
# Import the dependencies.
import pandas as pd
import requests
# Import the API key.
from config import g_key
import gmaps

In [2]:
# Pull saved city_data_df
city_data_df = pd.read_csv("WeatherPy_challenge.csv")
city_data_df

,City,City.1,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Surat Thani,TH,2020-02-24 05:05:33,9.14,99.33,106.00,58,20,10.29,few clouds,0.00,0.0
1,1,Butaritari,KI,2020-02-24 05:05:33,3.07,172.79,82.06,84,68,26.22,moderate rain,9.44,0.0
2,2,Lompoc,US,2020-02-24 05:05:33,34.64,-120.46,55.40,87,90,3.36,overcast clouds,0.00,0.0
3,3,Jumla,NP,2020-02-24 05:05:33,29.27,82.18,49.05,29,24,4.32,few clouds,0.00,0.0
4,4,Tiksi,RU,2020-02-24 05:05:34,71.69,128.87,-3.64,87,98,7.31,overcast clouds,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,621,Cavalcante,BR,2020-02-24 05:07:54,-13.80,-47.46,65.80,88,86,0.51,overcast clouds,0.00,0.0
622,622,Shingu,JP,2020-02-24 05:07:54,33.73,135.98,57.20,50,0,11.41,clear sky,0.00,0.0
623,623,Mahibadhoo,MV,2020-02-24 05:07:54,3.78,72.97,83.03,76,39,15.61,scattered clouds,0.00,0.0
624,624,Perth,AU,2020-02-24 05:07:25,-31.93,115.83,90.00,45,40,13.87,scattered clouds,0.00,0.0
625,625,Whyalla,AU,2020-02-24 05:07:55,-33.03,137.58,87.80,43,0,11.41,clear sky,0.00,0.0

In [3]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? -100
What is the maximum temperature you would like for your trip? 200

In [32]:
raining = input("Do you want it to be raining? (yes/no) ")
snowing = input("Do you want it to be snowing? (yes/no) ")

Do you want it to be raining? (yes/no) no
Do you want it to be snowing? (yes/no) no

In [33]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_temp_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
if raining == "yes":
    preferred_cities_temp_df = city_data_df.loc[(city_data_df["Rain inches (last 3 hrs)"] > 0)]

elif snowing == "yes":
    preferred_cities_temp_df = city_data_df.loc[(city_data_df["Snow inches (last 3 hrs)"] > 0)]
    
else:
    preferred_cities_temp_df = city_data_df.loc[(city_data_df["Rain inches (last 3 hrs)"] == 0) & \
                                               (city_data_df["Snow inches (last 3 hrs)"] == 0)]
preferred_cities_temp_df

,City,City.1,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Surat Thani,TH,2020-02-24 05:05:33,9.14,99.33,106.00,58,20,10.29,few clouds,0.0,0.0
2,2,Lompoc,US,2020-02-24 05:05:33,34.64,-120.46,55.40,87,90,3.36,overcast clouds,0.0,0.0
3,3,Jumla,NP,2020-02-24 05:05:33,29.27,82.18,49.05,29,24,4.32,few clouds,0.0,0.0
4,4,Tiksi,RU,2020-02-24 05:05:34,71.69,128.87,-3.64,87,98,7.31,overcast clouds,0.0,0.0
5,5,Ushuaia,AR,2020-02-24 05:03:05,-54.80,-68.30,42.80,70,75,25.28,light intensity drizzle,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,621,Cavalcante,BR,2020-02-24 05:07:54,-13.80,-47.46,65.80,88,86,0.51,overcast clouds,0.0,0.0
622,622,Shingu,JP,2020-02-24 05:07:54,33.73,135.98,57.20,50,0,11.41,clear sky,0.0,0.0
623,623,Mahibadhoo,MV,2020-02-24 05:07:54,3.78,72.97,83.03,76,39,15.61,scattered clouds,0.0,0.0
624,624,Perth,AU,2020-02-24 05:07:25,-31.93,115.83,90.00,45,40,13.87,scattered clouds,0.0,0.0
625,625,Whyalla,AU,2020-02-24 05:07:55,-33.03,137.58,87.80,43,0,11.41,clear sky,0.0,0.0

In [37]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp","Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""

# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        pass
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,TH,106.00,few clouds,9.14,99.33,Tapee Hotel
1,1,KI,82.06,moderate rain,3.07,172.79,Isles Sunset Lodge
2,2,US,55.40,overcast clouds,34.64,-120.46,Holiday Inn Express Lompoc
3,3,NP,49.05,few clouds,29.27,82.18,Hotel Sundar Rara Karnali
4,4,RU,-3.64,overcast clouds,71.69,128.87,Arktika
...,...,...,...,...,...,...,...
621,621,BR,65.80,overcast clouds,-13.80,-47.46,Pousada Vila dos IpÃªs
622,622,JP,57.20,clear sky,33.73,135.98,æ–°å®®ãƒ¦ãƒ¼ã‚¢ã‚¤ãƒ›ãƒ†ãƒ«
623,623,MV,83.03,scattered clouds,3.78,72.97,Omadhoo Inn
624,624,AU,90.00,scattered clouds,-31.93,115.83,Rendezvous Hotel Perth Central
625,625,AU,87.80,clear sky,-33.03,137.58,Foreshore Motor Inn

In [51]:
# Create the output file (CSV).
output_data_file = "WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City")

In [40]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
gmaps.configure(api_key=g_key)
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [48]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [49]:
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))